---
- name: Создание Ingress для основных сервисов
  template:
    src: ingress.yaml.j2
    dest: /tmp/k8s_resources/ingress.yaml

- name: Создание Ingress для Dashboard
  template:
    src: dashboard-ingress.yaml.j2
    dest: /tmp/k8s_resources/dashboard-ingress.yaml

- name: Применение YAML файлов для Ingress
  shell: "microk8s kubectl apply -f /tmp/k8s_resources/{{ item }}"
  loop:
    - ingress.yaml
    - dashboard-ingress.yaml
  register: apply_result
  changed_when: apply_result.rc == 0
